"""Add new column

Revision ID: 547a5373a871
Revises: b3058b6b4586
Create Date: 2019-11-24 19:51:01.890914

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '547a5373a871'
down_revision = 'b3058b6b4586'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('image_file', sa.String(length=20), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'image_file')
    # ### end Alembic commands ###
